---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: ${NS}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ${NS}-local-storage
  resources:
    requests:
      storage: 5Gi
