---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  namespace: ${NS}
data:
  application.properties: |-
    spring.datasource.url=jdbc:mysql://mysql:3306/test
    spring.datasource.username=${MYSQL_USER}
    spring.datasource.password=${MYSQL_PASSWORD}
    spring.jpa.hibernate.ddl-auto=update
