---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: springboot-sa
  namespace: ${NS}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: springboot-rb
  namespace: ${NS}
subjects:
  - kind: ServiceAccount
    name: springboot-sa
roleRef:
  kind: Role
  name: springboot-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: springboot-role
  namespace: ${NS}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "watch", "list"]

